#! /bin/sh
### BEGIN INIT INFO
# Provides: lan865x_init
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Load LAN865x driver
# Description: Load LAN865x MAC-PHY driver
### END INIT INFO

DRIVER_PATH="/home/pi/LAN8651_Installation/"

case "$1" in
	start)
		cd $DRIVER_PATH
		./load.sh
		cd -
		;;
	stop)
		;;
	restart)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
